# Generated by Django 5.1.4 on 2025-01-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel_banner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('banner_sub_text', models.CharField(max_length=100)),
                ('banner_image', models.ImageField(blank=True, default='jpg', upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='Travel_gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gallery_image', models.ImageField(blank=True, default='jpg', upload_to='image')),
                ('gallery_text', models.TextField()),
                ('gallery_price', models.IntegerField(default=0)),
            ],
        ),
    ]
