# Generated by Django 5.1.4 on 2025-01-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelhome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel_banner',
            name='banner_sub_text',
            field=models.CharField(max_length=255),
        ),
    ]
