# Generated by Django 5.1.4 on 2025-01-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelhome', '0002_alter_travel_banner_banner_sub_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel_banner',
            name='banner_text',
            field=models.CharField(default='Default Banner Text', max_length=255),
        ),
    ]
