# Generated by Django 5.1.4 on 2025-01-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelhome', '0003_travel_banner_banner_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel_gallery',
            name='gallery_title',
            field=models.CharField(default='Armenia', max_length=100),
        ),
    ]
