# Generated by Django 5.1.4 on 2025-01-15 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelhome', '0004_travel_gallery_gallery_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel_banner',
            name='video',
            field=models.FileField(null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='travel_banner',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='images_uploaded'),
        ),
    ]
