# Generated by Django 5.1.4 on 2025-01-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelhome', '0005_travel_banner_video_alter_travel_banner_banner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=255)),
                ('number_of_guests', models.IntegerField()),
                ('arrival_date', models.DateField()),
                ('leaving_date', models.DateField()),
            ],
        ),
    ]
