# Generated by Django 5.1.4 on 2025-01-22 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelhome', '0007_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='subjact',
            new_name='subject',
        ),
    ]
